version: "3.6"
services:
  api:
    image: nginx
    build: .
    ports:
      - 3001:3001
    restart: always
    env_file: .env
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: cetricka@gmail.com
      PGADMIN_DEFAULT_PASSWORD: Root
    ports:
      - "5050:80"
    depends_on:
      - db
volumes: 
  db-data: